# Repository configurations for pre-commit
repos:
  # isort configuration
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

  # Remove CRLF configuration
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.1.13
    hooks:
    -   id: remove-crlf

  # YAPF configuration
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf

  # pre-commit-hooks configurations
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
        exclude: 'cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention/cubin'
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: trailing-whitespace

  # Autoflake configuration
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.6.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']

  # Clang-format configuration
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
    -   id: clang-format
        types_or: [c++, c, cuda]
        exclude: |
            (?x)^(
                # Exclude the cubin files
                cpp/tensorrt_llm/kernels/contextF
